-- LDoc configuration file
-- luacheck: ignore
file = {
	"init.lua", "Dimensions.lua", "Autopos.lua", "Autosize.lua",
	"Node.lua", "Box.lua", "Text.lua", "Square.lua", "Border.lua", "List.lua",
	"Split.lua", "CollapseBase.lua", "Collapse.lua",
}
dir = "/mnt/c/Users/dante/Documents/ldoc/helium"
project = "helium"
title = "Helium reference"
format = "markdown"
not_luadoc = true
backtick_references = false
convert_opt = true
style = "../../.."